name: test-build-thoi-khoa-bieu-parser

env:
  DOCKER_HUB_USERNAME: tuana9a
  IMAGE_NAME: tuana9a/dkhptd-thoi-khoa-bieu-parser

on:
  push:
    branches:
      - "*"
      - "!main"
    paths:
      - "thoi-khoa-bieu-parser/**"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./thoi-khoa-bieu-parser
          file: ./thoi-khoa-bieu-parser/Dockerfile
          push: false
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Send notification
        if: always()
        shell: bash
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -H "Content-Type: application/json" \
            -d "{
              \"chat_id\":\"${{ secrets.TELEGRAM_CHAT_ID }}\",
              \"disable_notification\":true,
              \"text\":\"${{ job.status }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\\nimg: ${{ env.IMAGE_NAME }}\"
            }"
